spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    redis:
      host: localhost
      port: 6379
  config:
    activate:
      on-profile: test